steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'gcr.io/containers-244700/$REPO_NAME:$SHORT_SHA'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'gcr.io/containers-244700/$REPO_NAME:$SHORT_SHA'
images:
  - 'gcr.io/containers-244700/$REPO_NAME:$SHORT_SHA'
                                                  